name: Notify Teams on New Release

on:
  schedule:
    - cron: "0 * * * *"  # Check every hour (adjust as needed)
  workflow_dispatch: # Allow manual triggering

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release from the original repo
        id: latest_release
        run: |
          ORIGINAL_REPO="https://github.com/awslabs/amazon-eks-ami/releases/latest"
          response=$(curl -s $ORIGINAL_REPO)
          echo "Latest release info: $response"
          # Extract release name and URL
          tag_name=$(echo "$response" | jq -r .tag_name)
          release_url=$(echo "$response" | jq -r .html_url)
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "release_url=$release_url" >> $GITHUB_ENV

      - name: Send release notification to Teams
        run: |
          # Prepare the payload for Teams message
          webhook_url="${{ secrets.TEAMS_WEBHOOK_URL }}"
          payload=$(cat <<EOF
          {
            "title": "amazon-eks AMI has been released!",
            "text": "A new release has been published: [${{ env.tag_name }}](${{ env.release_url }})"
          }
          EOF
          )
          
          # Send the message
          curl -X POST -H "Content-Type: application/json" --data "$payload" $webhook_url
